[package]
name = "roguelike"
version = "0.1.0"
authors = ["'graysentinel' <kylen.wiggin@gmail.com>"]
edition = "2018"

[dependencies]
tcod = "0.14"
rand = "0.3.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"